"""empty message

Revision ID: 14775568851e
Revises: 3553585058c6
Create Date: 2016-06-07 17:50:19.939876

"""

# revision identifiers, used by Alembic.
revision = '14775568851e'
down_revision = '3553585058c6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('status', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'status')
    ### end Alembic commands ###
